const moviesData = {
    trending: [
        {
            id: 1,
            title: "Beyond Earth",
            year: 2019,
            category: "Movie",
            rating: "PG",
            image: "1.jpg",
            description: "A thrilling space exploration documentary that takes you beyond our planet.",
            duration: "2h 15m",
            genre: ["Documentary", "Space", "Science"],
            isTrending: true,
            isSaved: false,
            cast: ["Michael Anderson", "Emily Clarke", "David Chen"],
            director: "Sarah Johnson",
            trailer: "https://www.youtube.com/watch?v=example1"
        },
        {
            id: 2,
            title: "Bottom Gear",
            year: 2021,
            category: "Movie",
            rating: "PG",
            image: "2.jpg",
            description: "The ultimate car show with amazing stunts and reviews.",
            duration: "1h 45m",
            genre: ["Reality", "Cars", "Entertainment"],
            isTrending: true,
            isSaved: false,
            cast: ["James May", "Richard Hammond", "Jeremy Clarkson"],
            director: "Andy Wilman",
            trailer: "https://www.youtube.com/watch?v=example2"
        },
        {
            id: 3,
            title: "Undiscovered Cities",
            year: 2019,
            category: "TV Series",
            rating: "E",
            image: "3.jpg",
            description: "Explore hidden urban gems around the world.",
            duration: "8 Episodes",
            genre: ["Documentary", "Travel", "Culture"],
            isTrending: true,
            isSaved: false,
            cast: ["Maria Rodriguez", "John Smith"],
            director: "Alex Turner",
            trailer: "https://www.youtube.com/watch?v=example3"
        }
    ],
    recommended: [
        {
            id: 4,
            title: "The Great Lands",
            year: 2019,
            category: "Movie",
            rating: "E",
            image: "trend1.jpg",
            description: "A journey through Earth's most beautiful landscapes.",
            duration: "1h 55m",
            genre: ["Nature", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Robert Brown", "Lisa White"],
            director: "Christopher Nolan",
            trailer: "https://www.youtube.com/watch?v=example4"
        },
        {
            id: 5,
            title: "The Diary",
            year: 2019,
            category: "TV Series",
            rating: "PG",
            image: "trend2.jpg",
            description: "A dramatic series based on true events.",
            duration: "10 Episodes",
            genre: ["Drama", "History"],
            isTrending: false,
            isSaved: false,
            cast: ["Emma Watson", "Tom Hardy"],
            director: "David Fincher",
            trailer: "https://www.youtube.com/watch?v=example5"
        },
        {
            id: 6,
            title: "Earth's Untouched",
            year: 2017,
            category: "Movie",
            rating: "E",
            image: "trend3.jpg",
            description: "Discover places untouched by human civilization.",
            duration: "2h 5m",
            genre: ["Nature", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Morgan Freeman", "David Attenborough"],
            director: "Steven Spielberg",
            trailer: "https://www.youtube.com/watch?v=example6"
        },
        {
            id: 7,
            title: "No Land Beyond",
            year: 2019,
            category: "Movie",
            rating: "E",
            image: "4.jpg",
            description: "A thrilling adventure in uncharted territories.",
            duration: "1h 50m",
            genre: ["Adventure", "Action"],
            isTrending: false,
            isSaved: false,
            cast: ["Chris Hemsworth", "Scarlett Johansson"],
            director: "James Cameron",
            trailer: "https://www.youtube.com/watch?v=example7"
        },
        {
            id: 8,
            title: "During the Hunt",
            year: 2016,
            category: "TV Series",
            rating: "PG",
            image: "5.jpg",
            description: "Follow wildlife photographers on their dangerous missions.",
            duration: "6 Episodes",
            genre: ["Wildlife", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Steve Irwin", "Jane Goodall"],
            director: "Werner Herzog",
            trailer: "https://www.youtube.com/watch?v=example8"
        },
        {
            id: 9,
            title: "Autosport the Series",
            year: 2016,
            category: "TV Series",
            rating: "E",
            image: "6.jpg",
            description: "Behind the scenes of the world's biggest racing events.",
            duration: "12 Episodes",
            genre: ["Sport", "Racing"],
            isTrending: false,
            isSaved: false,
            cast: ["Lewis Hamilton", "Max Verstappen"],
            director: "Ron Howard",
            trailer: "https://www.youtube.com/watch?v=example9"
        },
        {
            id: 10,
            title: "Same Answer II",
            year: 2017,
            category: "Movie",
            rating: "E",
            image: "7.jpg",
            description: "The thrilling sequel to the mind-bending original.",
            duration: "2h 10m",
            genre: ["Thriller", "Mystery"],
            isTrending: false,
            isSaved: false,
            cast: ["Leonardo DiCaprio", "Ellen Page"],
            director: "Denis Villeneuve",
            trailer: "https://www.youtube.com/watch?v=example10"
        },
        {
            id: 11,
            title: "Below Echo",
            year: 2016,
            category: "TV Series",
            rating: "PG",
            image: "8.jpg",
            description: "A mysterious underwater adventure series.",
            duration: "8 Episodes",
            genre: ["Science Fiction", "Adventure"],
            isTrending: false,
            isSaved: false,
            cast: ["Jason Momoa", "Amber Heard"],
            director: "James Wan",
            trailer: "https://www.youtube.com/watch?v=example11"
        },
        {
            id: 12,
            title: "The Hidden Forest",
            year: 2022,
            category: "Movie",
            rating: "PG",
            image: "9.jpg",
            description: "Discover the secrets of an ancient forest ecosystem.",
            duration: "1h 58m",
            genre: ["Nature", "Mystery"],
            isTrending: false,
            isSaved: false,
            cast: ["Emma Stone", "Robert Pattinson"],
            director: "Guillermo del Toro",
            trailer: "https://www.youtube.com/watch?v=example12"
        },
        {
            id: 13,
            title: "Cyber Revolution",
            year: 2023,
            category: "TV Series",
            rating: "PG-13",
            image: "10.jpg",
            description: "A gripping tale of artificial intelligence and human destiny.",
            duration: "10 Episodes",
            genre: ["Sci-Fi", "Drama"],
            isTrending: false,
            isSaved: false,
            cast: ["Timothée Chalamet", "Zendaya"],
            director: "Alex Garland",
            trailer: "https://www.youtube.com/watch?v=example13"
        },
        {
            id: 14,
            title: "Ocean's Secrets",
            year: 2023,
            category: "Movie",
            rating: "E",
            image: "11.jpg",
            description: "Explore the deepest mysteries of our oceans.",
            duration: "2h 20m",
            genre: ["Documentary", "Nature"],
            isTrending: false,
            isSaved: false,
            cast: ["Sylvia Earle", "Philippe Cousteau"],
            director: "Jacques Perrin",
            trailer: "https://www.youtube.com/watch?v=example14"
        },
        {
            id: 15,
            title: "Interstellar Dreams",
            year: 2023,
            category: "Movie",
            rating: "PG-13",
            image: "12.jpg",
            description: "A visionary journey through space and time, exploring humanity's future among the stars.",
            duration: "2h 45m",
            genre: ["Sci-Fi", "Adventure", "Drama"],
            isTrending: false,
            isSaved: false,
            cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
            director: "Christopher Nolan",
            trailer: "https://www.youtube.com/watch?v=example15"
        },
        {
            id: 16,
            title: "Ancient Mysteries",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "13.jpg",
            description: "Uncover the secrets of ancient civilizations and their unexplained phenomena.",
            duration: "8 Episodes",
            genre: ["Documentary", "History", "Mystery"],
            isTrending: false,
            isSaved: false,
            cast: ["Morgan Freeman", "Neil deGrasse Tyson"],
            director: "Ken Burns",
            trailer: "https://www.youtube.com/watch?v=example16"
        },
        {
            id: 17,
            title: "Urban Legends",
            year: 2023,
            category: "TV Series",
            rating: "PG-13",
            image: "14.jpg",
            description: "A spine-chilling anthology series exploring famous urban legends from around the world.",
            duration: "10 Episodes",
            genre: ["Horror", "Mystery", "Thriller"],
            isTrending: false,
            isSaved: false,
            cast: ["Finn Wolfhard", "Millie Bobby Brown"],
            director: "Mike Flanagan",
            trailer: "https://www.youtube.com/watch?v=example17"
        },
        {
            id: 18,
            title: "Digital Frontier",
            year: 2023,
            category: "Movie",
            rating: "PG-13",
            image: "15.jpg",
            description: "A groundbreaking exploration of the metaverse and its impact on human connection.",
            duration: "2h 15m",
            genre: ["Sci-Fi", "Technology", "Drama"],
            isTrending: false,
            isSaved: false,
            cast: ["Ryan Gosling", "Ana de Armas"],
            director: "Denis Villeneuve",
            trailer: "https://www.youtube.com/watch?v=example18"
        },
        {
            id: 19,
            title: "Wild Symphony",
            year: 2023,
            category: "Movie",
            rating: "E",
            image: "16.jpg",
            description: "A breathtaking musical journey through nature's most spectacular performances.",
            duration: "1h 55m",
            genre: ["Documentary", "Music", "Nature"],
            isTrending: false,
            isSaved: false,
            cast: ["David Attenborough", "Hans Zimmer"],
            director: "Ron Howard",
            trailer: "https://www.youtube.com/watch?v=example19"
        },
        {
            id: 20,
            title: "Future Foods",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "17.jpg",
            description: "Explore innovative solutions to global food challenges and sustainable eating.",
            duration: "6 Episodes",
            genre: ["Documentary", "Science", "Food"],
            isTrending: false,
            isSaved: false,
            cast: ["Gordon Ramsay", "Anthony Bourdain"],
            director: "Morgan Neville",
            trailer: "https://www.youtube.com/watch?v=example20"
        },
        {
            id: 21,
            title: "Ocean's Secrets",
            year: 2023,
            category: "Documentary",
            rating: "PG",
            image: "18.jpg",
            description: "Dive deep into the unexplored mysteries of our oceans and discover incredible marine life.",
            duration: "1h 55m",
            genre: ["Documentary", "Nature", "Science"],
            isTrending: false,
            isSaved: false,
            cast: ["David Attenborough", "James Cameron"],
            director: "Jacques Cousteau",
            trailer: "https://www.youtube.com/watch?v=example21"
        },
        {
            id: 22,
            title: "Cyber Warriors",
            year: 2023,
            category: "TV Series",
            rating: "PG-13",
            image: "19.jpg",
            description: "Follow an elite team of cybersecurity experts as they protect the world from digital threats.",
            duration: "10 Episodes",
            genre: ["Action", "Technology", "Thriller"],
            isTrending: false,
            isSaved: false,
            cast: ["Sandra Oh", "Rami Malek", "Christian Slater"],
            director: "Sam Esmail",
            trailer: "https://www.youtube.com/watch?v=example22"
        },
        {
            id: 23,
            title: "Street Flavors",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "20.jpg",
            description: "A mouthwatering journey through the world's most vibrant street food cultures.",
            duration: "8 Episodes",
            genre: ["Food", "Travel", "Culture"],
            isTrending: false,
            isSaved: false,
            cast: ["Gordon Ramsay", "Anthony Bourdain", "David Chang"],
            director: "Roy Choi",
            trailer: "https://www.youtube.com/watch?v=example23"
        },
        {
            id: 24,
            title: "Quantum Minds",
            year: 2023,
            category: "Movie",
            rating: "PG-13",
            image: "21.jpg",
            description: "A mind-bending journey into the world of quantum physics and consciousness.",
            duration: "2h 10m",
            genre: ["Science", "Documentary", "Philosophy"],
            isTrending: false,
            isSaved: false,
            cast: ["Neil deGrasse Tyson", "Brian Greene", "Michio Kaku"],
            director: "Christopher Nolan",
            trailer: "https://www.youtube.com/watch?v=example24"
        },
        {
            id: 25,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "22.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 26,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "23.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 27,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "24.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 28,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "25.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 29,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "26.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 30,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "27.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
        {
            id: 31,
            title: "Urban Canvas",
            year: 2023,
            category: "TV Series",
            rating: "PG",
            image: "28.jpg",
            description: "Explore the vibrant world of street art and the artists who transform cities into galleries.",
            duration: "6 Episodes",
            genre: ["Art", "Culture", "Documentary"],
            isTrending: false,
            isSaved: false,
            cast: ["Banksy", "JR", "Shepard Fairey"],
            director: "Thierry Guetta",
            trailer: "https://www.youtube.com/watch?v=example25"
        },
    ]
};

export default moviesData;
